### TEST GET / WEBSITE
GET http://localhost:3000

### TEST GET / DASHBOARD
GET http://localhost:3000/dashboard

### TEST GET / DATA
GET http://localhost:3000/api/data

### DATA ENDPOINT FOR CREATING A USER
POST http://localhost:3000/api/data
Content-Type: application/json

{ 
  "name": "Thor"
}

### DELETE LAST ELEMENT FROM DATA
DELETE http://localhost:3000/api/data